const PAGE1 = {
  LOADING: 'PAGE_1_LOADING',
  FETCH_SUCCESS: 'PAGE_1_FETCH_SUCCESS',
  FETCH_FAILED: 'PAGE_1_FETCH_FAILED'
};
const PAGE2 = {
  LOADING: 'PAGE_2_LOADING',
  FETCH_SUCCESS: 'PAGE_2_FETCH_SUCCESS',
  FETCH_FAILED: 'PAGE_2_FETCH_FAILED'
};



const FAV_POST_DETAIL = {
  LOADING: 'FAV_POST_DETAIL_LOADING',
  FETCH_SUCCESS: 'FAV_POST_DETAIL_FETCH_SUCCESS',
  FETCH_FAILED: 'FAV_POST_DETAIL_FETCH_FAILED'
}

export { PAGE1 ,FAV_POST_DETAIL,PAGE2 };
